### ISSUE TITLE
M8Bot sometimes decides to ignore commands

### ISSUE THREAD

**Issue by DreamPhreak** [MAPReiff/M8-Bot#28]
Been adding streamers to the list, !add-streamer-twitch, but most of the time it just completely ignores the command. Then I copy-paste and send it again and then it works. As of writing this issue, I added 18 streamers, and only 2 of those were accepted on the first try.

Additionally, sometimes when doing the command a 2nd time, there seems to be a bit of lag on your server's end since it takes a few seconds to recognize the command then proceed to delete it and send the successful message.

**Comment by DreamPhreak** [comment]
Also happened with another command, !config-edit. Never recognized it.

**Comment by MAPReiff** [comment]
I will look into the issue with !add-streamer-twitch.
Also, !config-edit is not a command, the command is !config edit.

**Comment by DreamPhreak** [comment]
I figured out there was no hyphen in it after posting lol.
